### ISSUE TITLE
Adding new shortcuts to the search window

### ISSUE THREAD

**Issue by llinfeng** [tvjg/iswitchw#2]
I am fascinated by how well-developed the switcher is. It does everything I had in mind for an app-switcher, only to have made it better. 

**Question**: Where may I add the following shortcuts? Currently, I am deploying these mappings in my main AHK script (a separate one).
```
#IfWinActive ahk_exe AutoHotkey.exe
    ^w::
        Send {Ctrl Down}{Shift Down}{left}{Shift Up}{Ctrl Up}
        sleep 100
        SEnd {BS}
    return
    ^h:: Send {BS}
    ^k:: Send {Up}
    ^j:: Send {Down}
#IfWinActive 
```
I found that the search box is from the `ahk_exe AutoHotkey.exe` process, but none of these mappings work flawlessly:
1. `^w` does not work; yet issuing the physical keystrokes does the job;
2. `^h`, `^k` and `^j` only works for the first four consecutive presses when holding the Ctrl key. Beyond that, `^j` will be treated as a single keystroke `j`.

Thanks a lot!

All the best,

-Linfeng

**Comment by mcleodd10** [comment]
I'm not sure if you've moved on from this, it's been a few years after all, however I'd made a fairly significant number of changes to the look and feel of the program, and I've added the vim-esque shortcuts as well, if you want to give it a look:
https://github.com/evilmanimani/iswitchw

Cheers

**Comment by llinfeng** [comment]
@evilmanimani Thanks a lot for your new fork. The shortcuts are working as intended in your fork.
